test: :rocket: Add pipeline validate auto-install docker in EC2

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -33,6 +33,28 @@ jobs:
         echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
         chmod 600 key.pem
 
+    - name: Update system and install Docker if not present
+      run: |
+        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
+        # Update the system
+        sudo yum update -y
+
+        # Check if Docker is installed
+        if ! command -v docker &> /dev/null
+        then
+          echo "Docker not found, installing..."
+          sudo yum install -y docker
+          sudo systemctl start docker
+          sudo systemctl enable docker
+        else
+          echo "Docker is already installed."
+        fi
+
+        # Ensure Docker is running
+        sudo systemctl start docker
+        sudo systemctl enable docker
+        EOF
+
     - name: Stop running container
       run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} 'sudo docker stop my-html-app || true'
